# Generated by Django 4.2.1 on 2023-05-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docmentation', '0002_api_header_project_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='header',
        ),
    ]
